# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'evo.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(319, 158)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 321, 161))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.generationSize = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.generationSize.setMaximum(1000)
        self.generationSize.setProperty("value", 100)
        self.generationSize.setObjectName("generationSize")
        self.gridLayout.addWidget(self.generationSize, 0, 1, 1, 1)
        self.mutationRate = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.mutationRate.setSingleStep(1.0)
        self.mutationRate.setProperty("value", 0.1)
        self.mutationRate.setObjectName("mutationRate")
        self.gridLayout.addWidget(self.mutationRate, 1, 1, 1, 1)
        self.runButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.runButton.setObjectName("runButton")
        self.gridLayout.addWidget(self.runButton, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Generation Size"))
        self.runButton.setText(_translate("Dialog", "Run"))
        self.label_2.setText(_translate("Dialog", "Mutation Rate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
